services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 9003:9003
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    depends_on:
      - searxng
    ports:
      - 3009:3009
    volumes:
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3009/api
        - NEXT_PUBLIC_WS_URL=ws://localhost:3009
    depends_on:
      - perplexica-backend
    ports:
      - 3010:3010
    restart: unless-stopped


volumes:
  backend-dbstore:
